version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
    - 0.30.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
  - dependency-name: rollup-plugin-terser
    versions:
    - 7.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.0.0
